name: Deploy PR Preview

on:
  pull_request_target:
    branches:
      - dev
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy or Cleanup PR
        run: |
          export REMOTE_DIR="/home/ubuntu/CI-CD-test"
          export PR_ID="${{ github.event.pull_request.number }}"
          export BRANCH_NAME="${{ github.head_ref }}"
          export GITHUB_WORKSPACE="${GITHUB_WORKSPACE}"

          mkdir -p $REMOTE_DIR

          # Sync code to deployment directory
          rsync -av --delete $GITHUB_WORKSPACE/ $REMOTE_DIR/

          cd $REMOTE_DIR
          chmod +x deploy_pr.sh cleanup_pr.sh

          if [ "${{ github.event.action }}" = "closed" ]; then
            ./cleanup_pr.sh $PR_ID
          else
            ./deploy_pr.sh $PR_ID $BRANCH_NAME
          fi
