name: Deploy PR Preview

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy or Cleanup PR
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          BRANCH_NAME=${{ github.head_ref }}
          REPO_URL="https://github.com/${{ github.repository }}.git"
          REMOTE_DIR="/home/ubuntu/CI-CD-test"

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} <<EOF

            if [ ! -d "\$REMOTE_DIR" ]; then
              git clone \$REPO_URL \$REMOTE_DIR
            fi

            cd \$REMOTE_DIR
            git fetch origin
            git checkout dev
            git reset --hard origin/dev
            chmod +x *.sh

            if [ "${{ github.event.action }}" = "closed" ]; then
              bash cleanup_pr.sh \$PR_ID
            else
              bash deploy_pr.sh \$PR_ID \$BRANCH_NAME \$REPO_URL
            fi
          EOF
