name: CD

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << EOF
            if [ ! -d "/home/ubuntu/CI-CD-test" ]; then
              git clone https://github.com/Zahid031/CI-CD-test.git /home/ubuntu/CI-CD-test
            fi
            cd /home/ubuntu/CI-CD-test
            git fetch origin
            git reset --hard origin/dev
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
